import 'dart:io';
import 'package:flutter/foundation.dart';
import 'package:http/http.dart' as http;

import 'package:cloud_functions/cloud_functions.dart';

class GcsService {
  /// Uploads a local file directly to a Google Cloud Storage bucket using a signed URL.
  /// 
  /// The signed URL is a secure, temporary URL generated by your backend
  /// that grants the app write access to a specific GCS bucket path.
  Future<bool> uploadToGcs(File file, String signedUrl) async {
    try {
      final bytes = await file.readAsBytes();
      
      // Perform a PUT request with the file bytes directly to the GCS signed URL
      final response = await http.put(
        Uri.parse(signedUrl),
        headers: {
          'Content-Type': _guessMimeType(file.path),
        },
        body: bytes,
      );

      if (response.statusCode == 200 || response.statusCode == 201) {
        return true;
      } else {
        debugPrint('GCS upload failed: Status Code ${response.statusCode}');
        debugPrint('Response Body: ${response.body}');
        return false;
      }
    } catch (e) {
      debugPrint('Error uploading to GCS: $e');
      return false;
    }
  }

  /// Helper to get the correct MIME type header for standard extensions
  String _guessMimeType(String path) {
    if (path.endsWith('.pdf')) return 'application/pdf';
    if (path.endsWith('.png')) return 'image/png';
    if (path.endsWith('.jpg') || path.endsWith('.jpeg')) return 'image/jpeg';
    if (path.endsWith('.mp4')) return 'video/mp4';
    return 'application/octet-stream';
  }

  /// Fetches a signed URL from your backend service
  Future<Map<String, dynamic>?> fetchSignedUrl(String fileName) async {
    try {
      final HttpsCallable callable = FirebaseFunctions.instance.httpsCallable('generateSignedUrl');
      
      final response = await callable.call(<String, dynamic>{
        'fileName': fileName,
        'contentType': _guessMimeType(fileName),
      });

      // Returns a map containing 'signedUrl' and 'storagePath'
      return Map<String, dynamic>.from(response.data as Map);
    } catch (e) {
      debugPrint('Failed to get signed URL: $e');
      return null;
    }
  }
}
